name: rafeeky
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.7
  ionicons: ^0.2.2
  banner_carousel: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/home/
    - assets/
    - assets/home/illustrations/
    - assets/navbar/active/
    - assets/navbar/unactive/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Fonts/cairo.ttf
